language: r

cache: packages

matrix:
  include:
    - os: linux
      dist: trusty
      r: bioc-devel

r_packages:
  - devtools
  - covr
  - testthat
  - lintr
  - assertthat

bioc_packages:
  - BiocCheck
  - BiocStyle

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install --only-upgrade autoconf
  - sudo apt-get install --only-upgrade automake
  - sudo apt-get install --only-upgrade autotools-dev
  - sudo apt-get install autoconf-archive

before_script:
  - autoreconf -vif

env:
  global:
    - LINTR_COMMENT_BOT=false

after_success:
  - Rscript -e 'covr::codecov(); covr::coveralls()'
  - Rscript -e 'lintr::lint_package()'
  - R CMD BiocCheck $PKG_TARBALL
